### ISSUE TITLE
The `AppLast` is wrongly used or defined

### ISSUE THREAD

**Issue by ped7g** [WHumphreys/Manic-Miner-Source-Code#1]
The `AppLast  EQU *-1 ; The last used byte's address.` correctly states that it is address of last **used** byte.

But then the tape saving commands set length as `AppLast-AppFirst`. Unless zeus requires length-1, this is bug, not storing the last byte of graphics defined.

I guess the most natural fix would be AppLast  EQU * ; The first unused byte's address.`
Then the expression `AppLast-AppFirst` returns actual amount of "used" bytes.

**Comment by WHumphreys** [comment]
Well spotted :-)
